# Generated by Django 4.0.1 on 2022-02-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_f_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_l_name',
        ),
    ]
