# Generated by Django 4.0.1 on 2022-02-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_default_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_f_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_l_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
