# Generated by Django 4.0.1 on 2022-02-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_userprofile_default_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_full_name',
        ),
    ]
