# Generated by Django 4.0.1 on 2022-03-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile_default_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_first_name',
            new_name='default_f_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_last_name',
            new_name='default_l_name',
        ),
    ]
