# Generated by Django 4.0.1 on 2022-03-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_rename_default_first_name_userprofile_default_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_l_name',
        ),
    ]
