# Generated by Django 4.0.1 on 2022-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='original_order',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
