# Generated by Django 4.0.1 on 2022-02-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutorder_original_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='country',
            field=models.CharField(default='GB', max_length=2),
        ),
    ]
