# Generated by Django 4.0.1 on 2022-02-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkoutorder_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='country',
        ),
    ]
