# Generated by Django 4.0.1 on 2022-02-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_checkoutorder_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutorder',
            old_name='f_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='checkoutorder',
            name='l_name',
        ),
    ]
