# Generated by Django 4.0.1 on 2022-03-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_full_name_checkoutorder_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutorder',
            name='l_name',
        ),
    ]
