# Generated by Django 4.0.1 on 2022-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='postcode',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_name1',
            field=models.CharField(default=2, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street_name2',
            field=models.CharField(default=3, max_length=254),
            preserve_default=False,
        ),
    ]
