# Generated by Django 4.0.1 on 2022-03-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_address_options_rename_address_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_name2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street_name1', 'street_name2', 'city', 'postcode', 'phone_number')},
        ),
    ]
