# Generated by Django 4.0.1 on 2022-03-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_address_street_name2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_text', models.TextField(max_length=1024)),
            ],
        ),
    ]
