# Generated by Django 4.0.1 on 2022-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_herotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotext',
            name='hero_header',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
