# Generated by Django 4.0.1 on 2022-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
        migrations.AddField(
            model_name='product',
            name='toppings',
            field=models.ManyToManyField(to='products.Topping'),
        ),
    ]
