# Generated by Django 4.0.1 on 2022-02-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_size_delete_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_name',
            field=models.CharField(max_length=254, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.ImageField(default=1, upload_to='', verbose_name='Product Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price_l',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price for Large'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_m',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price for Medium'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_s',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Price for Small'),
        ),
    ]
