# Generated by Django 4.0.1 on 2022-02-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_product_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='full_name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='image_path',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
