# Generated by Django 4.0.1 on 2022-02-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_full_name_pizza_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='display_name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
