# Generated by Django 4.0.1 on 2022-02-04 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(max_length=254, null=True)),
                ('price_s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_m', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_l', models.DecimalField(decimal_places=2, max_digits=4)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, default='2', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
