# Generated by Django 4.0.1 on 2022-02-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ManyToManyField(default='2', to='products.Category'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ManyToManyField(default='1', to='products.Category'),
        ),
    ]
