# Generated by Django 4.0.1 on 2022-02-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_drink_category_drink_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='category',
        ),
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
